### PR TITLE
Climate and xarray Lecture + Lab06

### PR DESCRIPTION
**Pull request by facusapienza21**
This includes the contents from Chelle's lecture with the xarray tutorial modified and with more comments. It also includes the Lab06 for this Friday with the xarray practice. A version of the JupyterBook can be found [here](https://facusapienza21.github.io/stat159-site/index.html).

I am planning to make some more changes here, including the RA for next week and some small changes in both the lectures and lab for Friday, but I think this is a good starting point to integrate the xarray contents in the course website.

### CODE REVIEW

**Comment by fperez** [comment]
Spelling notes: 
-"assumption of obserbartions" -> "assumption of observations".
- "is internally desing" -> "is internally designed"
- "are radicually different" -> "are radically different"
- "multidimensioal data" -> "multidimensional data"
- "cordinate variables" -> "coordinate variables"

I'm sure there's more, but no worries - I know you're typing super fast while the lectures are happening, and it's very annoying to edit a doc like that without spellcheck support. I've just [added](https://github.com/berkeley-dsep-infra/datahub/pull/4344) the jupyterlab spellcheck package, which I hope will make this more convenient (I should have done it before!). I haven't used it myself, but let's see how it goes, hopefully it will make the environment more pleasant for all of us.

**Comment by fperez** [comment]
OK, with the spellcheck extension (currently only on staging), cells in the notebook with spelling errors are much easier to work with:

image

You can right-click on them to get a context menu with suggested corrections:

image

We'll get this merged into prod quickly, but in the meantime you can use the staging hub if you want to work on these and fix some of the spelling issues.

**Comment by fperez** [comment]
Subletting -> subsetting (in xarray notebook)

**Comment by fperez** [comment]
In the testing one - "Optimization is the route to all evil" -> "Premature optimization is the root of all evil" (it's a [famous quote in CS](https://ubiquity.acm.org/article.cfm?id=1513451#:~:text=Trying%20to%20do%20the%20optimization,best%20practice%20among%20software%20engineers.)).

**Comment by fperez** [comment]
This is great though - we'll iterate further, and it will be easier to polish this much new text with a spell checker in place :) 

Thanks for the work! Merging now so you can use it in lab tomorrow and we'll continue refining. Thanks!

**Comment by facusapienza21** [comment]
This is lovely @fperez! Finally I will be able to do the spell check much faster and efficient. I am terrible with this even in Spanish and I always switch characters and I don't see the difference unless I have a grammar spelling tool. Thank you!

**Pull request merged**
